config/routes.rb
Rails.application.routes.draw do
  resources :weddings do
    resources :wedding_guests do
      collection { post :import }
      get :invitation_response, on: :member
      patch :rsvp, on: :member
      get :send_one_invite, on: :member
    end
    resources :expenses
    put :toggle_user, on: :collection
    get :send_invites, on: :member
    get :search_restaurants, on: :member
    get :book_restaurant, on: :member
    # put 'import', on: :member
  end

  resources :invites


  # resources :wedding_guests do
    # collection { post :import }
  # end

  devise_for :users, controllers: {
  invitations: "invitations"
}
  root to: 'pages#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get :search_users, controller: :searches
  get :get_all_planners, controller:"pages"

end

app/models/wedding_guest.rb
require 'csv'
# require 'smarter_csv'
class WeddingGuest < ActiveRecord::Base
  belongs_to :wedding
  has_one :wedding_invite
  after_create :set_confirmation_token
  enum attending: [:unspecified, :accepted, :declined], _suffix: true #https://api.rubyonrails.org/v5.2.3/classes/ActiveRecord/Enum.html   cauta dupa same
  enum plus_one: [:no, :yes, :unspecified], _suffix: true
  enum menu: [:normal, :vegetarian, :unspecified], _suffix: true

  def self.import(file, wedding_id)
    options = {headers: true, encoding: "ISO-8859-1", row_sep: :auto}
    CSV.foreach(file.path, headers: true) do |row|
      WeddingGuest.create!(
        name: row["name"], 
        table: row["table"], 
        wedding_id: wedding_id, 
        email: row["email"], 
        attending: :unspecified,
        menu: :unspecified, 
        plus_one: :unspecified, 
        confirm_token: SecureRandom.urlsafe_base64.to_s
      ) unless WeddingGuest.where(email: row["email"], wedding_id: wedding_id).exists?
    end
  end

  def add_options(attendance, plus_one, menu)
    self.attending = attendance if attendance.present?
    self.plus_one = plus_one if plus_one.present?
    self.menu = menu if menu.present?
    self.confirm_token = nil
    self.save
  end

  def set_confirmation_token
    if self.confirm_token.blank?
      self.confirm_token = SecureRandom.urlsafe_base64.to_s
    end
    self.save
  end
end

app/controllers/wedding_guests_controller.rb
class WeddingGuestsController < ApplicationController
  # before_action :authenticate_user!, only:[]
  before_action :set_wedding_guest, only: [:show, :edit, :update, :destroy, :invitation_response]
  before_action :set_wedding_with_permission, only: [:invitation_response, :rsvp]
  before_action :set_wedding, except: [:invitation_response, :rsvp]

  def index
    @wedding_guests = WeddingGuest.where(wedding_id: @wedding.id)
  end

  def show
  end

  def new
    @wedding_guest = WeddingGuest.new
  end

  def edit
  end

  def create
    is_part_of_wedding?(current_user, @wedding)
    if WeddingGuest.where(email: wedding_guest_params["email"]).exists?
      flash[:notice] = "Guest already exists"
      redirect_back(fallback_location: root_path) 
    else
      @wedding_guest = WeddingGuest.new(wedding_guest_params)
      @wedding_guest.wedding_id = @wedding.id
      @wedding_guest.attending = :unspecified
      @wedding_guest.menu = :unspecified
      @wedding_guest.plus_one = :unspecified
      respond_to do |format|
        if @wedding_guest.save
          format.html { redirect_to wedding_wedding_guest_path(@wedding,@wedding_guest), notice: 'Wedding guest was successfully created.' }
          format.json { render :index, status: :created, location: @wedding_guest }
        else
          format.html { render :new }
          format.json { render json: @wedding_guest.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @wedding_guest.update(wedding_guest_params)
        format.html { redirect_to wedding_wedding_guest_url(@wedding,@wedding_guest), notice: 'Wedding guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @wedding_guest }
      else
        format.html { render :edit }
        format.json { render json: @wedding_guest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @wedding_guest.destroy
    respond_to do |format|
      format.html { redirect_to wedding_wedding_guests_url(@wedding), notice: 'Wedding guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    WeddingGuest.import(params[:file], params[:wedding_id]) unless params[:file].nil?
    redirect_to wedding_wedding_guests_path(@wedding), notice: "Wedding Guests Added Successfully!"
  end

  def invitation_response
  end

  def rsvp
    token = params["wedding_guest"]["token"]
    unless token.blank?
      guest = WeddingGuest.where(confirm_token: token).first
      guest.add_options(params["wedding_guest"]["attending"], params["wedding_guest"]["plus_one"], params["wedding_guest"]["menu"])
      flash[:notice] = "Thank you for responding!"
      redirect_to wedding_path(params["wedding_id"])
    end
  end

  def send_one_invite
    wedding = Wedding.find(params.dig("wedding_id"))
    wedding_guest = WeddingGuest.find(params.dig("id"))
    WeddingGuestMailer.attendance_confirmation(wedding_guest, wedding).deliver_now
    flash[:notice] = "Invitation sent successfully"
    redirect_to wedding_wedding_guests_path(@wedding)
  end

  private
  def set_wedding_guest
    @wedding_guest = WeddingGuest.find(params[:id])
  end

  def wedding_guest_params
    params.require(:wedding_guest).permit(:name, :table, :email, :attending, :plus_one, :menu, :wedding_id)
  end

  def set_wedding
    @wedding = Wedding.find(params[:wedding_id])
    is_part_of_wedding?(current_user, @wedding)
  end

  def set_wedding_with_permission
    @wedding = Wedding.find(params[:wedding_id])
  end
end

app/helpers/wedding_guests_helper.rb
module WeddingGuestsHelper
  def method_and_url
    if @wedding_guest.persisted?
      {
        method: :put,
        url: wedding_wedding_guest_path(@wedding, @wedding_guest)
      }
    else
      {
        method: :post,
        url: wedding_wedding_guests_path(wedding_id: @wedding.id)
      }
    end
  end

    def m_u
    if @expense.persisted?
      {
        method: :put,
        url: wedding_expense_path(@wedding, @expense)
      }
    else
      {
        method: :post,
        url: wedding_expenses_path(wedding_id: @wedding.id)
      }
    end
  end
end

app/views/wedding_guests/_form.html.erb
<div class="row justify-content-center">
<%= form_with(model: @wedding_guest, local: true, **method_and_url, html: { class: 'col-6' }) do |form| %>
  <% if @wedding_guest.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@wedding_guest.errors.count, "error") %> prohibited this wedding_guest from being saved:</h2>

      <ul>
      <% @wedding_guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :table %>
    <%= form.number_field :table, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/wedding_guests/edit.html.erb
<%= link_to 'Back', wedding_wedding_guests_path(@wedding), class: 'btn btn-link' %>
<h1 class="text-center mt-2 mb-5">Editing Wedding Guest</h1>

<%= render 'form', wedding_guest: @wedding_guest %>

app/views/wedding_guests/index.html.erb
<%= link_to 'Back to the wedding page', wedding_path(@wedding), data: { turbolinks: false }, class: 'btn btn-link pl-0' %>
<br>
<br>
<div class="justify-content-between d-flex">
  <h2 class="mb-2 d-flex">Wedding Guests</h2>
  <div>
  <% unless @wedding_guests.size == 0 %>
    <%= link_to 'Send Invitations', send_invites_wedding_path(@wedding) unless current_user.planner? %>
    &nbsp;
    &nbsp;
  <% end %>
    <%= link_to 'New Wedding Guest', new_wedding_wedding_guest_path  unless current_user.planner? %>
  </div>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Table</th>
      <th scope="col">Attendance</th>
      <th scope="col">Plus One</th>
      <th scope="col">Menu</th>

      <th colspan="10" scope="col"></th>
    </tr>
  </thead>
  <tbody>
     <% @wedding_guests.each.with_index(1) do |wedding_guest, index| %>
      <tr>
        <th scope="row"><%= index %></th>
        <td><%= wedding_guest.name %></td>
        <td><%= wedding_guest.email %></td>
        <td><%= wedding_guest.table %></td>
        <% if wedding_guest.nil? %>
          <td><%= wedding_guest.attending %></td>
          <td><%= wedding_guest.plus_one %></td>
          <td><%= wedding_guest.menu %></td>
        <% else %>
          <td><%= wedding_guest.attending.titlecase %></td>
          <td><%= wedding_guest.plus_one.titlecase %></td>
          <td><%= wedding_guest.menu.titlecase %></td>
        <% end %>

        <td><%= link_to 'Show', wedding_wedding_guest_path(@wedding, wedding_guest) unless current_user.planner?%></td>
        <td><%= link_to 'Edit', edit_wedding_wedding_guest_path(@wedding, wedding_guest) unless current_user.planner?%></td>
        <td><%= link_to 'Destroy', wedding_wedding_guest_path(@wedding, wedding_guest), method: :delete, class: 'text-danger', data: { confirm: 'Are you sure?' } unless current_user.planner?%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% unless current_user.planner? %>
  <h3 class="mt-5">Import Guest List</h3>
  <%= form_tag import_wedding_wedding_guests_path, multipart: true do %>
    <div class="form-group">
      <%= file_field_tag :file %>
      <%= submit_tag "Upload guest list", class: 'btn btn-primary' %>
    </div>
  <% end %>
<% end %>
<!-- <div class="d-flex flex-column bd-highlight mb-3">
  <div class="p-2 bd-highlight"><%= link_to 'Send Invitations', send_invites_wedding_path(@wedding) %> </div>
</div> -->

app/views/wedding_guests/invitation_response.html.erb
<div class="row justify-content-center">
  <%= form_for @wedding_guest, url: rsvp_wedding_wedding_guest_path(@wedding, @wedding_guest) do |f| %>
    <%= f.hidden_field :token, value: params["token"] %>
    <div class="form-group">
      <%= f.label :attending, "Will you be attending our wedding?" %><br />
      <%= f.radio_button :attending, 'accepted' %> Yes<br />
      <%= f.radio_button :attending, 'declined' %> No<br />
<!--       <%= f.label :attending, "Will you be attending our wedding?" %><br />
      <%= f.label :attending, "Yes", :value => "attending"  %>
      <%= f.radio_button :attending, true %>
      <%= f.label :attending, "No", :value => "declined" %>
      <%= f.radio_button :attending, false%> -->
    </div>
    <div class="form-group">
      <%= f.label :plus_one, "Will you be accompanied?" %><br />
      <%= f.radio_button :plus_one, 'yes' %> Yes<br />
      <%= f.radio_button :plus_one, 'no' %> No<br />
<!--       <%= f.label :plus_one, "Yes", :value => "yes"  %>
      <%= f.radio_button :plus_one, true %>
      <%= f.label :plus_one, "No", :value => "no" %>
      <%= f.radio_button :plus_one, false, :checked => true %> -->
    </div>
    <div class="form-group">
      <%= f.label :menu, "Do you want a vegetarian menu?" %><br />
      <%= f.radio_button :menu, 'vegetarian' %> Yes<br />
      <%= f.radio_button :menu, 'normal' %> No<br />
<!--       <%= f.label :menu, "Yes", :value => "normal"  %>
      <%= f.radio_button :menu, true %>
      <%= f.label :menu, "No", :value => "vegetarian" %>
      <%= f.radio_button :menu, false, :checked => true %> -->
    </div>
    <div class="form-group">

      <%= f.submit "Send response", class: 'btn btn-primary' %>
    </div>

  <% end %>
</div>

app/views/wedding_guests/new.html.erb
<%= link_to 'Back', wedding_wedding_guests_path(@wedding), class: 'btn btn-link' %>
<h1 class="text-center mt-2 mb-5">New Wedding Guest</h1>

<%= render 'form'  %>

app/views/wedding_guests/show.html.erb
<div class="justify-content-between d-flex">
  <h2 class="mb-2 d-flex"><%= @wedding_guest.name %></h2>
  <div>
    <%= link_to 'Send invitation', send_one_invite_wedding_wedding_guest_path(@wedding, @wedding_guest), class: 'btn btn-link', class: 'btn btn-link', data: { turbolinks: false } %>
     <%= link_to 'Edit', edit_wedding_wedding_guest_path(@wedding,@wedding_guest), class: 'btn btn-link', data: { turbolinks: false } %>
  </div>
</div>

<p>
  <strong>Table:</strong>
  <%= @wedding_guest.table %>
</p>

<p>
  <strong>Attending:</strong>
  <%= @wedding_guest.attending.titlecase %>
</p>

<p>
  <strong>Plus one:</strong>
  <%= @wedding_guest.plus_one.titlecase %>
</p>

<p>
  <strong>Menu:</strong>
  <%= @wedding_guest.menu.titlecase %>
</p>

<%= link_to 'Back', wedding_wedding_guests_path(@wedding) %>