config/routes.rb
Rails.application.routes.draw do
  resources :weddings do
    resources :wedding_guests do
      collection { post :import }
      get :invitation_response, on: :member
      patch :rsvp, on: :member
      get :send_one_invite, on: :member
    end
    resources :expenses
    put :toggle_user, on: :collection
    get :send_invites, on: :member
    get :search_restaurants, on: :member
    get :book_restaurant, on: :member
    # put 'import', on: :member
  end

  resources :invites


  # resources :wedding_guests do
    # collection { post :import }
  # end

  devise_for :users, controllers: {
  invitations: "invitations"
}
  root to: 'pages#index'
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get :search_users, controller: :searches
  get :get_all_planners, controller:"pages"

end

app/models/wedding.rb
class Wedding < ApplicationRecord
  has_many :wedding_guests, foreign_key: "wedding_id", dependent: :destroy
  # has_many :wedding_gifts, foreign_key: "wedding_id", dependent: :destroy
  has_many :user_weddings, dependent: :destroy
  has_many :users, through: :user_weddings
  has_many :wedding_invitations
  has_many :expenses
  has_one_attached :avatar

  geocoded_by :address
  after_validation :geocode

  def toggle_user(user_id)
    if user_weddings.pluck(:user_id).include?(user_id)
      user_weddings.where(user_id: user_id).destroy_all
      return true
    else
      if user_weddings.size < 2
        user_weddings << UserWedding.create(wedding_id: id, user_id: user_id)
        return true
      end
    end

    false
  end

  def full_info_filled?
    %i[restaurant_name address date].map do |field|
      send(field)
    end.all?
  end
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  require 'google_places'

  before_action :authenticate_user!, except: :show
  before_action :find_wedding, only: %i[send_invites search_restaurants update edit book_restaurant set_location]
  before_action :find_wedding_with_no_permission, only: :show
  before_action :check_if_planner, only: %i[create, new]
  before_action :check_toggled_users, only: :create
  before_action :initialize_new_wedding, only: :new
  before_action :set_location, only: :show
  after_action :set_location, only: :update
  @@toggled_users = []

  def index
    @weddings = User.find(current_user.id).weddings
  end

  def show
    @bride = @wedding.users.bride.first
    @groom = @wedding.users.groom.first
  end

  def new
    if current_user.planner?
      if @search.present?
        @name = @search["name"]
        @users = @users.search(@name)
      end
    end
  end

  def toggle_user
    user_id = params[:user_id].to_i

    toggled = if user_id.in?(@@toggled_users)
      @@toggled_users -= [user_id]
      true
    elsif @@toggled_users.size < 2
        @@toggled_users << user_id
      true
    else
      false
    end

    render json: {
      remaining_users: 2 - @@toggled_users.size,
      toggled: toggled,
      ids: @@toggled_users
    }
  end

  def create
    if check_toggled_users && bride_and_groom
      @wedding = Wedding.new
      @wedding.users << User.find(@@toggled_users)
      @wedding.users << current_user
      @wedding.currency = params.dig("wedding", "currency")
      @wedding.total_budget = params.dig("wedding", "total_budget")
      @wedding.name = @wedding.users.first.name.split.first + " & " +@wedding.users.second.name.split.first + "'s wedding"

      if params.dig("wedding", "avatar").present?
        @wedding.avatar.attach(params["wedding"]["avatar"])
      else
        @wedding.avatar.attach(io: File.open('app/assets/images/default_wedding_avatar.jpg'), filename: 'placeholder.jpg', content_type: 'image/jpg')
      end

      if @wedding.save
        @@toggled_users = []
        redirect_to @wedding
      else
         flash[:error] = @wedding.errors.full_messages.to_sentence
        initialize_new_wedding

        render 'new'
      end
    else
      initialize_new_wedding
      render 'new'
    end
  end

  def update
    if @wedding.update(wedding_params)
      @wedding.avatar.attach(update_params["avatar"]) unless update_params["avatar"].nil?
      flash[:notice] = "Wedding updated successfully!"
      set_location
      render 'show', data: { turbolinks: false }
    else
      flash[:error] = @wedding.errors
      render 'edit'
    end
  end

  def send_invites
    guests = WeddingGuest.where(wedding_id: params["id"])
    guests.each do |guest|
      WeddingGuestMailer.attendance_confirmation(guest, @wedding).deliver_now
    end
    flash[:notice] = "Invitations sent successfully"
    redirect_to wedding_wedding_guests_path(@wedding)
    # redirect_back(fallback_location: root_path)
  end

  def search_restaurants
    unless params[:query].nil?
      @client = GooglePlaces::Client.new(ENV["GOOGLE_API_KEY"])
      @spots = @client.spots_by_query(params[:query], types: ['restaurant'], detail: true)
    end
    #  multe rezultate la wedding bucuresti
    # ca sa dai catre google palces url te uiti aici https://stackoverflow.com/questions/30467556/how-do-i-get-a-direct-link-to-a-place-on-google-maps-with-the-place-id
    # o sa te fol de place id
  end

  def book_restaurant
    @wedding.update(restaurant_name: params[:name], address: params[:address], latitude: params[:latitude], longitude: params[:longitude])
    render 'edit'
  end

  def set_location
    return @hash = {} if @wedding.address.nil? || @wedding.address.blank?

    unless @wedding.latitude.nil? || @wedding.longitude.nil? #daca nu se schimba lat si lon dupa aschimbarea doar a adresei atunci n verifica ca alt si lon sunt nil ci doar ca adresa nu e
      @hash = [{ lat: @wedding.latitude, lng: @wedding.longitude}]
    else
      @hash = get_latitude_and_longitude
    end

    return @hash
  end

  private

  def get_latitude_and_longitude
    result = Geocoder.search(@wedding.address).first.coordinates
    lat_lng_hash = Gmaps4rails.build_markers(@wedding) do |wedding, marker|
      marker.lat result.first
      marker.lng result.second
    end
    return [lat_lng_hash]
  end

  def initialize_new_wedding
    @@toggled_users = []
    @wedding = Wedding.new
    @users = User.includes(:user_weddings).where(user_weddings: { user_id: nil }).where.not(role: "planner")
    @search = params["search"]
  end

  def find_wedding
    @wedding = Wedding.find(params[:id])
  end

  def find_wedding_with_no_permission
    @wedding = Wedding.find(params[:id])
  end

  def update_params
    params.require(:wedding).permit(:avatar)
  end

  def wedding_params
    params.require(:wedding).permit(:restaurant_name, :address, :date, :total_budget, :bride_info, :groom_info, :invitation_text, :currency)
  end

  def check_toggled_users
    if @@toggled_users.size < 2
      flash[:notice] = "You must select 2 users."
      false
    else
      true
    end
  end

  def bride_and_groom
    if User.find(@@toggled_users.first).role != User.find(@@toggled_users.second).role
      true
    else
      flash[:notice] = "You must select a bride and a groom"
      false
    end
  end

end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/weddings/book_restaurant.html.erb
<!-- <h2 class="text-center mt-2 mb-5">Add The Date of the wedding </h2>

<div class="row justify-content-center">

  <%= form_for(@wedding, url: wedding_path(@wedding), url: { action: "update" }, html: { class: 'col-6' }) do |f| %>
    <div class="form-group">
      <%= f.label "Restaurant's name" %>
      <%= f.text_field :restaurant_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label "The address of the restaurants" %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label "The date of the wedding" %>
      <br>
      <%= f.datetime_select :wedding_date, :placeholder => 'dd/mm/yyyy', class: 'form-control datepicker' %>
    </div>
    <div class="form-group">
    </div>
    <div class="form-group">
      <%= f.label "Wedding Photo" %>
      <%= f.file_field :avatar, class: 'form-control-file' %>
    </div>
    <div class="form-group">
      <%= f.submit nil, class: 'btn btn-primary mt-4' %>
    </div>
  <% end %>
</div>
 -->

app/views/weddings/edit.html.erb
<h2 class="text-center mt-2 mb-5">Edit wedding</h2>

<div class="row justify-content-center">

  <%= form_for(@wedding, url: wedding_path(@wedding), url: { action: "update" }, html: { class: 'col-6' }) do |f| %>
    <% if current_user.planner? %>
      <div class="form-group">
        <%= f.label "Restaurant's name" %>
        <%= f.text_field :restaurant_name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label "The address of the restaurants" %>
        <%= f.text_field :address, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label "The date of the wedding" %>
        <br>
        <% if @wedding.date.nil? || @wedding.date.blank? %>
          <%= f.datetime_select :date, class: 'form-control datepicker', default: Time.now %>
        <% else %>
          <%= f.datetime_select :date, class: 'form-control datepicker', default: @wedding.date %>
        <% end %>
      </div>
      <div class="form-group">
        <%= f.label :total_budget %>
        <%= f.number_field :total_budget, class: 'form-control' %>
      </div>
      <div id="form-group">
        <%= f.label "Currency" %>
        <%= f.text_field :currency, class: 'form-control', required: true %>
      </div>
    <% end %>
    <% if current_user.bride? || current_user.groom?%>
      <div class="form-group">
        <%= f.label "Wedding Photo" %>
        <%= f.file_field :avatar, class: 'form-control-file' %>
      </div>
      
    <% end %>

    <% if current_user.bride? %>
      <div class="form-group">
        <%= f.label "Your description" %>
        <%= f.text_area :bride_info, class: 'form-control', rows: 7 %>
      </div>
    <% end %>

    <% if current_user.groom? %>
      <div class="form-group">
        <%= f.label "Your description" %>
        <%= f.text_area :groom_info, class: 'form-control', rows: 7 %>
      </div>
    <% end %>


    <% if current_user.groom? || current_user.bride?%>
      <div class="form-group">
        <%= f.label "Your Wedding invitation text" %>
        <%= f.text_area :invitation_text, class: 'form-control', rows: 10 %>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.submit nil, class: 'btn btn-primary mt-4' %>
    </div>
  <% end %>
</div>

app/views/weddings/index.html.erb
<div class="justify-content-between d-flex my-4">
  <h2 class="d-flex">Your weddings</h2>
  <div>
    <%= link_to 'New Wedding', new_wedding_path, data: { turbolinks: false } %>
  </div>
</div>

<% if @weddings.count.positive? %>
<div class="row justify-content-md-center justify-content-xl-between">
  <% @weddings.each do |wedding| %>
    <div class="card m-2" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <%= image_tag(wedding.avatar, class: 'card-img-top h-100') %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= link_to wedding.name, wedding_url(wedding), data: { turbolinks: false } %></h5>
            <p class="card-text">
              <%= fa_icon("user") %>
              <small class="text-muted">
                <%= link_to(pluralize(wedding.wedding_guests.count, 'guest'), wedding_wedding_guests_url(wedding)) %>
              </small>
            </p>
              <p class="card-text">
                <%= fa_icon("map") %>
                <small class="text-muted">
                  <%= wedding.restaurant_name.present? ? wedding.restaurant_name : 'Restaurant not chosen yet.' %>
                </small>
              </p>
              <p class="card-text">
                <%= fa_icon("map-marker") %>
                <small class="text-muted">
                  <%= wedding.address.present? ? wedding.address : 'Address not chosen yet.' %>
                </small>
              </p>
              <p class="card-text">
                <%= fa_icon("calendar") %>
                <small class="text-muted">
                  <%= wedding.date.present? ? wedding.date.strftime("%d-%m-%Y, %H:%M") : 'Date not chosen yet.'%>
                </small>
              </p>
              <p class="card-text">
                <%= fa_icon("money") %>
                <small class="text-muted">
                  Budget: 
                  <% if wedding.total_budget.present? %> 
                    <% if wedding.currency == "USD" %>
                      $<%= wedding.total_budget %>
                    <% elsif  wedding.currency == "EUR" %>
                      <%= wedding.total_budget %>€
                    <% else %>
                      <%= wedding.total_budget %> <%= wedding.currency %>
                    <% end %>
                  <% else %>
                    not set yet
                  <% end %>
                </small>
              </p>
              <p class="card-text">
                <%= fa_icon("money") %>
                <small class="text-muted">
                  <% if wedding.expenses.present? %>
                    <% if wedding.currency == "USD" %>
                      <%= link_to("Total expenses: $#{ wedding.expenses.sum(:price) }", wedding_expenses_url(wedding)) %>
                    <% elsif wedding.currency == "EUR" %>
                      <%= link_to("Total expenses: #{ wedding.expenses.sum(:price) }€", wedding_expenses_url(wedding)) %>
                    <% else %>
                      <%= link_to("Total expenses: #{ wedding.expenses.sum(:price) }", wedding_expenses_url(wedding)) %> <%= wedding.currency %>
                    <% end %>
                  <% else %>
                     <%= link_to("No expenses added yet", wedding_expenses_url(wedding)) %>
                  <% end %>
                </small>
              </p>
          </div>
        </div>
      </div>
    </div>

  <% end %>
</div>
<% else %>
  <div class="text-center p-5">
    You have no weddings. <%= link_to 'Start by creating one.', new_wedding_path, data: { turbolinks: false } %>
  </div>
<% end %>

app/views/weddings/new.html.erb
<h2 class="text-center mt-2 mb-5">Create a new wedding</h2>

<div class="row justify-content-center">

  <%= form_for(@wedding, html: { class: 'col-12' }) do |f| %>

    <%= hidden_field_tag :selected_ids %>

    <h3>Choose bride & groom</h3>

    <div id="weddings-new-invitees-wrapper">
      <%= javascript_pack_tag 'weddings' %>
    </div>

    <div id="form-group">
      <%= f.label "Currency" %>
      <%= f.text_field :currency, class: 'form-control', required: true %>
    </div>

    <div class="form-group">
      <%= f.label :total_budget %>
      <%= f.number_field :total_budget, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit "Create Wedding", class: 'btn btn-primary mt-4' %>
    </div>
  <% end %>
</div>

app/views/weddings/search_restaurants.html.erb
<%= link_to 'Back to the wedding page', wedding_path(@wedding), class: 'btn btn-link pl-0' %>
<br>
<br>
<h2 class="my-3">Search restaurants</h2>

<div class="field">
  <%= form_tag(search_restaurants_wedding_path(@wedding), method: :get, class: 'form form-horizontal mt-5') do %>
  <div class="form-row align-items-center">
  <div class="col-4">
    <%= text_field_tag(:query, params[:query], class: 'form-control', placeholder: 'Enter your criterias') %>
    </div>
    <div class="col-auto">
    <%= submit_tag("Search", class: 'btn btn-primary') %>
    </div>
    </div>
  <% end %>
</div>
<br>
<br>


<% unless @spots.nil? %>
<div class="row justify-content-md-center justify-content-xl-between">
  <% @spots.each do |spot| %>
    <div class="card m-2" style="max-width: 540px;">
      <div class="row no-gutters">
        <div class="col-md-4">
          <% unless spot.photos[0].nil? %>
            <img src="<%= spot.photos[0].fetch_url(400) %>" class="card-img-top h-100">
          <% end %>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"> <%= spot.name %> </h5>
            <p class="card-text">
              <%= fa_icon("map") %>
              <small class="text-muted">
                <%= spot.formatted_address.present? ? spot.formatted_address : "Address not available" %>
              </small>
            </p>
            <p class="card-text">
              <%= fa_icon("phone") %>
              <small class="text-muted">
                <%= spot.formatted_phone_number.present? ? spot.formatted_phone_number : "Phone number not available" %>
              </small>
            </p>
            <p class="card-text">
              <%= fa_icon("star") %>
              <small class="text-muted">
                <%= spot.rating.present? ? spot.rating : "Rating not available" %>
              </small>
            </p>
            <p class="card-text">
              <%= fa_icon("link") %>
              <small class="text-muted">
                <a href="https://www.google.com/maps/search/?api=1&query=Google&query_place_id=<%= spot.place_id %>" cass="btn btn-primary stretched-link">Link to the restaurant's page on Google Maps</a>
              </small>
            </p>
            <% if current_user.planner? %>
              <p class="card-text">
                <%= fa_icon("bookmark") %>
                <small class="text-muted">
                  <%= link_to "Book the restaurant", book_restaurant_wedding_path(name: spot.name, address: spot.formatted_address, latitude: spot.lat, longitude: spot.lng) %>
                </small>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/weddings/show.html.erb
<div class="card border-0" style="background: transparent;">
  <%= image_tag(@wedding.avatar, class: 'card-img-top', style: 'height: 20rem;') %>
  <div class="card-body pl-2">
    <h3 class="card-title"><%= @wedding.name %>
      <% unless @wedding.date.nil? %>
      <span class="text-muted">|</span>
      <div id="clockdiv" class="text-muted">
        <span class="days"></span> days,
        <span class="hours"></span> hours,
        <span class="minutes"></span> minutes,
        <span class="seconds"></span> seconds
      </div>
      <% end %>
    </h3>
    <% unless current_user.nil? %>
      <%= link_to 'Edit Wedding', edit_wedding_path, class: 'card-link', data: { turbolinks: false } %>
      <% if @wedding.restaurant_name.nil? || @wedding.restaurant_name.blank? %>
        <%= link_to 'Search Restaurant', search_restaurants_wedding_path, class: 'card-link', data: { turbolinks: false } %>
      <% else %>
        <%= link_to 'Search Another Restaurant', search_restaurants_wedding_path, class: 'card-link', data: { turbolinks: false } %>
      <% end %>
    <% end %>
  </div>
</div>
<% unless current_user.nil? %>
  <div class="row pl-3">
  <div class="col-4 mt-3">
   <p class="card-text">
    <%= fa_icon("user") %>
    <small class="text-muted">
      <%= link_to(pluralize(@wedding.wedding_guests.count, 'guest'), wedding_wedding_guests_path(@wedding)) %>
    </small>
  </p></div>
  <div class="col-4 mt-3">
    <p class="card-text">
      <%= fa_icon("map") %>
      <small class="text-muted">
        <%= @wedding.restaurant_name.present? ? @wedding.restaurant_name : 'Restaurant not chosen yet.' %>
      </small>
    </p></div>
    <div class="col-4 mt-3">
    <p class="card-text">
      <%= fa_icon("map-marker") %>
      <small class="text-muted">
        <%= @wedding.address.present? ? @wedding.address : 'Address not chosen yet.' %>
      </small>
    </p></div>
    <div class="col-4 mt-3">
    <p class="card-text">
      <%= fa_icon("calendar") %>
      <small class="text-muted">
        <%= @wedding.date.present? ? @wedding.date.strftime("%d-%m-%Y, %H:%M") : 'Date not chosen yet.'%>
      </small>
    </p></div>

    <% unless current_user.nil? %>
    <div class="col-4 mt-3">
      <p class="card-text">
        <%= fa_icon("money") %>
        <small class="text-muted">
          Budget:
          <% if @wedding.total_budget.present? %>
            <% if @wedding.currency == "USD" %>
              $<%= @wedding.total_budget %>
            <% elsif  @wedding.currency == "EUR" %>
              <%= @wedding.total_budget %>€
            <% else %>
              <%= @wedding.total_budget %> <%= @wedding.currency %>
            <% end %>
          <% else %>
            not set yet
          <% end %>
        </small>
      </p></div>
      <div class="col-4 mt-3">
      <p class="card-text">
        <%= fa_icon("money") %>
        <small class="text-muted">
          <% if @wedding.expenses.present? %>
            <% if @wedding.currency == "USD" %>
              <%= link_to("Total expenses: $#{ @wedding.expenses.sum(:price) }", wedding_expenses_url(@wedding)) %>
            <% elsif @wedding.currency == "EUR" %>
              <%= link_to("Total expenses: #{ @wedding.expenses.sum(:price) }€", wedding_expenses_url(@wedding)) %>
            <% else %>
              <%= link_to("Total expenses: #{ @wedding.expenses.sum(:price) } #{ @wedding.currency }", wedding_expenses_url(@wedding)) %> 
            <% end %>
          <% else %>
             <%= link_to("No expenses added yet", wedding_expenses_url(@wedding)) %>
          <% end %>
        </small>
      </p></div>
    <% end %>
  </div>
<% end %>
<h2 class="text-center text-italic mt-5">Bride & Groom</h2>

<div class="row mt-5">
  <% if @wedding.users.bride.first.present? %>
    <div class="col-6">
      <div class="text-center">
        <%= avatar_for(@wedding.users.bride.first, size: 250) %>
      </div>
      <h3 class="text-center mt-3"><%= @wedding.users.bride.first.name %></h3>
      <div class="text-muted text-italic p-5 mt-5 rounded main-application-container">
        <%= simple_format(@wedding.bride_info) %>
      </div>
  <% end %>
  </div>
  <% if @wedding.users.groom.first.present? %>
    <div class="col-6">
    <div class="text-center">
      <%= avatar_for(@wedding.users.groom.first, size: 250) %>
    </div>
      <h3 class="text-center mt-3"><%= @wedding.users.groom.first.name %></h3>
      <div class="text-muted text-italic p-5 mt-5 rounded main-application-container">
        <%= simple_format(@wedding.groom_info) %>
      </div>
    </div>
  <% end %>
</div>

<% if @wedding.full_info_filled? %>
<div class="row my-5">
  <div class="col-12">
    <h4 class="text-italic text-muted text-center rounded main-application-container p-5">
      The wedding will take place on
      <%= @wedding.date.strftime("%d-%m-%Y, %H:%M") %>,
      at <%= @wedding.restaurant_name %> (<%= @wedding.address %>).
    </h4>
  </div>
</div>
<% end %>

<div class="row mb-5">
  <div class="col-12">
  <%= hidden_field_tag("wedding_date", @wedding.date) %>

<script src="//maps.google.com/maps/api/js?key=<%= ENV["GOOGLE_API_KEY"] %>"></script>
<script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
<script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>

 <% unless @wedding.address.nil? || @wedding.address.blank? %>
    <div style='width: 100%;'>
    <div id="map" style='width: 100%; height: 400px;'></div>
    </div>
    <script type="text/javascript">
      handler = Gmaps.build('Google');
      handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        handler.getMap().setZoom(18);
        Gmaps4Rails.map.setZoom(1);
      });
    </script>
<%end%>
</div>
</div>